### PR TITLE
Add linux

### PR DESCRIPTION
**Pull request by TaYaKi71751**
# Related Issues
- project-violet/violet/issues/258
- project-violet/violet/issues/271
> - 39d30920f8584fdc60558d5ae4aa0e71dac983fb
- project-violet/violet/issues/269
> - d8ce02eeebdcbb8e49a2e2dc0cc1341e6e346758
> - 4557107fdd6168c25716a962ce1768e51527c523
> - 57800dfe236d52f139178e58ae3c7bc1761a0542
> - 9dbac26f4ed64642db03b0aaf56cd5b9cb63c285
- project-violet/violet/issues/273
> - a4002eeb0e5ca0dcd86a9998022398ace60d95ff
- project-violet/violet/issues/222
> - f4b0469d85a8fc209d0fe508c20282b91568b9f2
> - 64881265c6a951340204d0617a40923a18db2828

-   (wontfix) Support Firebase in linux-build [library was only for Andoid/iOS](https://pub.dev/packages/firebase_analytics)
- [x] Add 7zr for linux-build
- [x] Add read cookies from firefox for linux-build

### CODE REVIEW

**Comment by TaYaKi71751** [comment]
image
image

**Comment by TaYaKi71751** [comment]
Tested on AppImage
image

**Comment by TaYaKi71751** [comment]
It was caused by missing `libquickjs_c_bridge_plugin.so`

**Comment by TaYaKi71751** [comment]
image

**Comment by TaYaKi71751** [comment]
`overflow:hidden;`
image

**Comment by TaYaKi71751** [comment]
but this also a bug
image

**Comment by TaYaKi71751** [comment]
image

**Comment by TaYaKi71751** [comment]
image

**Comment by TaYaKi71751** [comment]
Another to fix for linux-build
image

**Comment by TaYaKi71751** [comment]
_TagSelectorDialogState

**Comment by TaYaKi71751** [comment]
image

**Comment by TaYaKi71751** [comment]
to fix this text chip size
image

**Comment by TaYaKi71751** [comment]
image

**Comment by TaYaKi71751** [comment]
image

**Comment by TaYaKi71751** [comment]
https://github.com/TaYaKi71751/violet/releases/tag/latest-9dbac26f4ed64642db03b0aaf56cd5b9cb63c285

**Comment by TaYaKi71751** [comment]
https://github.com/TaYaKi71751/violet/releases/tag/latest-a2803ed5270a42a593c8002aae4d368383a6d885

**Comment by TaYaKi71751** [comment]
project-violet/violet/issues/273

**Comment by TaYaKi71751** [comment]
https://github.com/TaYaKi71751/violet/releases/tag/latest-5eb68fa3348df9b14d7e944d66c4208a1205f220

**Comment by violet-dev** [comment]
혹시 리뷰해도 되는 걸까요?

**Comment by TaYaKi71751** [comment]
https://github.com/TaYaKi71751/violet/releases/tag/latest-ba260c11d489ee92306dc45bc46d5b30fd3f31a8

**Comment by TaYaKi71751** [comment]
> 혹시 리뷰해도 되는 걸까요?

```예```

**Comment by violet-dev** [comment]
변경 사항이 굉장히 많은데요, 이 pr은 그대로 놔둔 상태에서 본문의 내용대로 linux 지원과 독립된 issue는 cherry-pick해서 새로운 pr로 올려주시면 감사하겠습니다.
그대로 리뷰하기엔 양이 많아서 감당이 안될 것 같네요 😢

**Comment by TaYaKi71751** [comment]
- project-violet/violet/pull/278
- project-violet/violet/pull/277
두개의 pr로 분리 하였습니다.

**Comment by TaYaKi71751** [comment]
this branch was moved to [dev-archive1](https://github.com/TaYaKi71751/violet/tree/dev-archive1)

**Pull request closed without merging**
