### PR TITLE
Fix forEach issue for eh-bookmark

### PR DESCRIPTION
**Pull request by TaYaKi71751**
# Related Issue
- project-violet/violet/issues/282
> - [Add duckduckgo for ehash](https://github.com/project-violet/violet/pull/280/commits/f1379bb9734ac014ad81be80cfe387f31eaf840c)
> - [Use duckduckgo search with proxied request](https://github.com/project-violet/violet/pull/280/commits/36c1436af6f745778637b09108d8f522fea3ca1b)
> - [Add cache for ehash](https://github.com/project-violet/violet/pull/280/commits/5d5da2510822c3d5d93873d2e2d538e78322e952)
- https://stackoverflow.com/questions/42467663/how-to-async-await-in-list-foreach-in-dart
> - [Fix forEach issue for eh-bookmark](https://github.com/project-violet/violet/pull/280/commits/196517c214c56cd2d4daab3f9e3c7afed847eed5)
> - [Use loading](https://github.com/project-violet/violet/pull/280/commits/cbee9717cd0839f4073eeb2e8f749cf496fc3bde)
> - [Use same index with loading](https://github.com/project-violet/violet/pull/280/commits/e4201228db78afa3d15593839ca8883a8a0a6545)

### CODE REVIEW

**Comment by TaYaKi71751** [comment]
https://stackoverflow.com/questions/42467663/how-to-async-await-in-list-foreach-in-dart

**Comment by TaYaKi71751** [comment]
I tested on Android
- when use `articleList.forEach((element) async {})`
> - Bookmark wasn't loaded
- when use `await Future.forEach(articleList,(element) async {})`
> - Bookmark was loaded

**Comment by TaYaKi71751** [comment]
# BUT 
[Use loading](https://github.com/project-violet/violet/pull/280/commits/cbee9717cd0839f4073eeb2e8f749cf496fc3bde)
was worked too

**Comment by TaYaKi71751** [comment]
some gallery_token could not be search by `?next=${(id) + 1}`
then just add use duckduckgo when could not be search by ``?next=${(id) + 1}``

**Comment by TaYaKi71751** [comment]
I need to add proxied duckduckgo search

**Comment by TaYaKi71751** [comment]
Just can watch tags on bookmark page
Screenshot_20231227-150437

**Comment by TaYaKi71751** [comment]
But, sadly cannot search ehash with exhentai.org only galleries :(

**Comment by TaYaKi71751** [comment]
> But, sadly couldn't search ehash with exhentai.org only galleries by proxied duckduckgo search :(

But don't recommend request with 0000000000 ~ ffffffffff
because 
image

**Comment by TaYaKi71751** [comment]
I need to add this

**Comment by TaYaKi71751** [comment]
sadly
image

**Comment by TaYaKi71751** [comment]
@TaYaKi71751
[Add exhentai to idSearch](https://github.com/project-violet/violet/pull/280/commits/025ec179ace152431de59d311f79e105039e7e02)
It was also fix exhentai only download issue
image

**Comment by TaYaKi71751** [comment]
maybe timeout should be optional because on using 1.1.1.1 WARP on 400kbps it slow always timeout

**Comment by TaYaKi71751** [comment]
# TODO
use loading screen without throw
Screenshot_20231229-125550

**Comment by TaYaKi71751** [comment]
Screenshot_20231229-151708
Screenshot_20231229-151726
Screenshot_20231229-151718

**Comment by TaYaKi71751** [comment]
I need to fix this

**Comment by violet-dev** [comment]
flutter formatter 한 번 돌려주시면 감사하겠습니다!

**Comment by TaYaKi71751** [comment]
git pull --rebase 후 수정 후 dart format . 진행 하겟습니다.

**Comment by TaYaKi71751** [comment]
build workflow 확인 후 `dart format .` 진행 하겟습니다.

**Comment by TaYaKi71751** [comment]
`dart format .` 후 커밋 하였습니다.

**Comment by TaYaKi71751** [comment]
https://github.com/TaYaKi71751/violet/pull/7

**Comment by TaYaKi71751** [comment]
머 지하여 도될가요

**Comment by TaYaKi71751** [comment]
moved to https://github.com/project-violet/violet/pull/292
with https://github.com/TaYaKi71751/violet/pull/8 (merge to upstream)

**Pull request closed without merging**
